### ISSUE TITLE
Map tiles don't display after two geosearches

### ISSUE THREAD

**Issue by nickpeihl** [SJCGIS/water-systems#3]
Steps to reproduce: 
1) Search for address (ex. 76 Vineyard Ln)
2) Search for Hannah (as in Hannah Rd)

Map turns grey until the map is panned. Zoom has no effect.

**Comment by npeihl** [comment]
Seems to be fixed with Esri-Leaflet 1.0.0

**Comment by nickpeihl** [comment]
Fixed by 1aeaa7cd67f70d4e7666f1670c3fd3d469c4373a
